# Generated by Django 4.1.2 on 2022-11-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Company_Information',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Company_Name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
